### ISSUE TITLE
how do i load this into krunker?

### ISSUE THREAD

**Issue by edsbrand** [hrt/KrunkerMultihack#11]
step by step please. :)

**Comment by hrt** [comment]
0. Clone/download this repository and extract it into a folder.
1. Visit chrome://extensions (via omnibox or menu -> Tools -> Extensions).
2. Enable Developer mode by ticking the checkbox in the upper-right corner.
3. Click on the "Load unpacked extension..." button.
4. Select the extracted directory.


now krunker io will play with the hack loaded

**Comment by THEGUY3ds** [comment]
There is a tutorial here: https://youtu.be/qY_4KiFpuQQ
