### ISSUE TITLE
Thx for ur work so far! *FEATURE REQUEST*

### ISSUE THREAD

**Issue by THEGUY3ds** [hrt/KrunkerMultihack#12]
Their one was a krunker.io hack called funk and had a disguise feature to spoof your name so you wouldn't get banned. It would be good if you could add that thx.

**Comment by hrt** [comment]
I can change your name locally but I doubt you can change your username like that.

Could just log out to be a guest

**Comment by ghost** [comment]
hi HRT, you got any website or any telegram?
your krunker.io hack is so good that i wanna follow you on website or telegram. 
thx

**Comment by hrt** [comment]
Lol nah, but I do post my work on YouTube if I'm allowed

**Comment by ghost** [comment]
okay i will follow you on Youtube. thank you

**Comment by hrt** [comment]
Got into a game whilst debugging and it bugged out and showed everyone I was a guest whilst logged in and gaining KR. Clearly something can be abused here.

![image](https://user-images.githubusercontent.com/21159953/62643954-b706f500-b966-11e9-9893-1ec07b33f23e.png)

**Comment by hrt** [comment]
Works by logging in just before the game ends, you appear as guest but KR gets added

**Comment by GreatCheat** [comment]
I noticed that bug earlier, looks even when i cheated on my account, people called me "Guest_x is a hacker"...
