### ISSUE TITLE
I cant play.

### ISSUE THREAD

**Issue by J-Queso** [hrt/KrunkerMultihack#13]
It keeps in "CONNECTING..." And i cant enter or do anything with the new adjust of Fake Lag .
I dont why it happens, but it would be very cool if u can fix it, take your time, its hard to do hacks and i know it takes time, but i hope it gets fixed! :)

**Comment by J-Queso** [comment]
Nvm with the "bug" update now its gone, thanks! (U can close this)

**Comment by hrt** [comment]
Yeah it was a bug with fake lag that got fixed.
