### ISSUE TITLE
Freezes mid-game 

### ISSUE THREAD

**Issue by doosvult** [hrt/KrunkerMultihack#14]
When playing the Infect game mode, right after the "Infection countdown" is complete, the game often freezes, I suppose when you are not the first one infected. However, the time in the upper-left, the chat box, kill feed, and list of players in the upper right, turning red (infected) all keep working. Only the player, along with the enemy tags, are frozen.
Edit:
I have found this issue to be present in other game modes as well, such as Gun Game. I think this only occurs in game modes strictly available in Custom.

**Comment by hrt** [comment]
I'll look into it later. This isn't surprising since I've never played a non normal game.

**Comment by hrt** [comment]
Hey is this freeze only a few seconds or do you need to refresh

**Comment by hrt** [comment]
Posted a fix please re-download and tell me if it still freezes

**Comment by wazzey** [comment]
We need to refresh when it freezes but i dont have the time to check rn.

**Comment by wazzey** [comment]
Doesnt freeze
