### ISSUE TITLE
New "anti-cheat"

### ISSUE THREAD

**Issue by GreatCheat** [hrt/KrunkerMultihack#18]
Devs released new version of Krunker with new "anti cheat", which makes unable to find any game lobby to these who is using Your extension.

Thanks in advance, buddy.

**Comment by GreatCheat** [comment]
Pics under adresses below:

1) https://ibb.co/kmcw3wf

2) https://ibb.co/DMJmPZd

**Comment by wazzey** [comment]
Thanks for update bro.

**Comment by hrt** [comment]
Haha this is great. I was getting bored and they just updated with "anti-cheat" for 1.4.8: https://krunker.io/docs/versions.txt

**Comment by GreatCheat** [comment]
Right after update there was kind of anomaly which put all avalaible users of your cheat on the same server in the same game room. Man that was so hilarious, people spinning here and there :)

**Comment by hrt** [comment]
@GreatCheat If I had to guess, that's probably because my extension block Krunker from updating (for these kinds of circumstances). And Krunker probably automatically placed all the old version users together.

**Comment by Armanta** [comment]
Keep up the good work man.

Do you have discord?

**Comment by hrt** [comment]
Pushed an update,

I didn't find any "anti cheat" updates on client side.

**Comment by hrt** [comment]
@Armanta  I don't post my discord public because they've closed my account before
