### ISSUE TITLE
Keybinds and Aimbot

### ISSUE THREAD

**Issue by J-Queso** [hrt/KrunkerMultihack#2]
Can u improve the aimbot? I know its hard to make a cheat and it takes time, but if u can improve it would be greatful, and u can add keybinds to activate or descactivate the functions? Would be great too, and btw please dont make 3 ammo all weapons i wanna use Ak, and please make a option for the aimbot to aim to head or body cause sometimes the aimbot get higher than the head of the opponent.

Keep the good work dude!

**Comment by hrt** [comment]
3 ammo wasn't intentional, will fix when I wake up.

As for the rest, we'll have to see

**Comment by hrt** [comment]
3 ammo was fixed,

Making user interfaces like hack menus / settings / key binds are so anti productive and boring. These settings can also be changed in the code itself. Unless everyone wants it I'm not gonna be doing it.
