### ISSUE TITLE
Need to fix aimbot

### ISSUE THREAD

**Issue by wazzey** [hrt/KrunkerMultihack#23]
Could you make sure to stop the aimbot from shooting on the wall when its closer to the enemy , + one question: What's anti-aim?
If i've said any mistakes please make sure to correct me

**Comment by hrt** [comment]
Is this issue regarding shooting targets that can't be hit yet?

**Comment by GreatCheat** [comment]
Yep, aimbot aims and shots enemies behind wooden crates.

**Comment by hrt** [comment]
Yeah I've been wanting to fix this, will try when I have energy

**Comment by wazzey** [comment]
Thanks :)
btw i did this is this fine?
https://greasyfork.org/en/scripts/388248-read-below

**Comment by hrt** [comment]
Sure

**Comment by hrt** [comment]
I have pushed a fix please try again.

Also on this update it should automatically shoot through walls that can be shot through.
