### ISSUE TITLE
Krunker 1.4.9

### ISSUE THREAD

**Issue by GreatCheat** [hrt/KrunkerMultihack#28]
Hello, devs released new version of Krunker, could you please update your cheat?

Can you provide public info how did you bypassed anti-cheat this time? For educational purposes only :)

**Comment by hrt** [comment]
All anti cheat things are mentioned in readme. If they add something new I will discuss it in the read me.


I'm at a wedding and need sleep after so you might have to wait

**Comment by GreatCheat** [comment]
Thank you, enjoy the wedding :)

**Comment by THEGUY3ds** [comment]
THX

**Comment by hrt** [comment]
updated for 1.4.9, might take a few minutes for the auto update to update.
