### ISSUE TITLE
Solution for this kind of situation 

### ISSUE THREAD

**Issue by doosvult** [hrt/KrunkerMultihack#29]
![image](https://user-images.githubusercontent.com/53782869/62637363-4da4c900-b909-11e9-9b0f-13791ed70ee8.png)

**Comment by hrt** [comment]
Not gonna lie, I don't think my cheat is blocking you from picking up the weapon if this is what you're hinting at. Difficult to test but from looking at the code, it shouldn't be interfering with game inputs.

If there's an easy way for me to test/debug this situation I can fix it.

**Comment by hrt** [comment]
Just tested picking up weapons on the same map myself and it works fine, seems more like a krunker or server bug/glitch to me (not caused by me)
