### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by coolboy10121416** [hrt/KrunkerMultihack#3]
1. The aimbot does not lock on  more then 90% of the time.
2. Why are u only getting 2 bullets.
3. we need a hack menu and some keybinds. 
Its a good hack so far but i just wanted u to know the bugs.

**Comment by hrt** [comment]
Cool

**Comment by hrt** [comment]
Making user interfaces like hack menus / settings / key binds are so anti productive and boring. These settings can also be changed in the code itself. Unless everyone wants it I'm not gonna be doing it.
