### ISSUE TITLE
Sniper on aim zoom don't work

### ISSUE THREAD

**Issue by tilenpirih** [hrt/KrunkerMultihack#30]
When I'm aiming with my sniper the zoom don't work. I don't know why because I didn't look source code but please fix it. I'm using version 1.4.7

**Comment by hrt** [comment]
Yeah I've removed zoom on all weapons because it's just irritating and useless lol

**Comment by tilenpirih** [comment]
Ok. you're kinda right. I don't know but for sniper I prefer zoom. Maybe you could add button to enable and disable that feature. And in this version there is a white line outside the player which is for me annoying. Isn't enough just to have name, healthbar and weapon at the top? And maybe you instead of controlling cheats menu with letters g,h,j,k,l,l,... you use function keys (F1, F2, F3,...) because otherwise you have porblems typing in chat because you change the settings too, or you can just have one key that isn't used often to lock the settings (1 key to the left of the number 1 on keyboard) If I'm gonna have some extra time I can modify it in your code. Otherwise good job with the hack.

**Comment by hrt** [comment]
@tilenpirih settings aren't changed if you are typing in chat, make sure you're using the latest version.

the whtie box is quite useful beacuse of how hitboxes work in the game:  https://www.youtube.com/watch?v=xzlnzJoQAS8

I'll consider changing / removing them

**Comment by tilenpirih** [comment]
@hrt Yeah I know but those white boxes are quite distracting because you actually can't see a player, specially if you are far away. Anyway, thanks for listening and replying to me.

**Comment by GreatCheat** [comment]
These boxes doesn't distract me at all :P.

No worries my friend @tilenpirih, you'll get used to it :)
