### ISSUE TITLE
Krunker.io 1.5.0 update

### ISSUE THREAD

**Issue by GreatCheat** [hrt/KrunkerMultihack#32]
Hello Friend,
Krunker got updated to version 1.5.0, which updated its Anti-Cheat.

>   == UPDATE 1.5.0 ==
>  - Added Melee Kills Stat to Accounts
>  - Fixed Knife Search in Marketplace
>  - Fixed Knife Previews in Spins
>  - Bandwidth Optimization on Server
>  - Can now Search for Knives with Keyword Knife in store
>  - Anti Cheat Update
>  - Added Scroll direction Setting

Thank you in advance, 
Have a nice day :)

**Comment by hrt** [comment]
Yeah well unfortunately there's a lot of people copy pasting this cheat and changing the name claiming it's their work. 

I think it's time to stop posting things public.

**Comment by GreatCheat** [comment]
Don't worry my Friend, you have whole history of developement of your cheat here, on GitHub. 
Some people will always try to claim others' work, but they can be eaisly exposed.

You have fanbase right here and for us all Your work matters. If you need some help or ideas with developement, just ask!

**Comment by drinkingwaterisgood** [comment]
I'm willing to pay for your hard work, permanent or monthly

**Comment by GreatCheat** [comment]
I can do this too, when we all decide to keep it private and not to share it to avoid such unpleasant situations...

**Comment by hrt** [comment]
Fuck that

**Comment by hrt** [comment]
You won't catch me selling cheats

**Comment by GreatCheat** [comment]
What if you continue doing what you're good at, and we become your patrons, just like patronite? I watched your previous projects and enjoyed it. But honestly i always was a huge fan of breaking anti-cheats.

**Comment by hrt** [comment]
Not a terrible idea

**Comment by GreatCheat** [comment]
Take your time to think about it Friend. Good night.

**Comment by hrt** [comment]
I'm no longer releasing anything publicly yet.
Going down the patreon route for now, https://www.patreon.com/hrt
