### ISSUE TITLE
update pls

### ISSUE THREAD

**Issue by coolboy1012141612** [hrt/KrunkerMultihack#33]
@hrt its simple add something like cheats made by you like remove the click to play i put
cheats made by hrt or something and obfuscate your code pls because i dont want people to steal your coding so pls obfuscate it

**Comment by hrt** [comment]
Watermarks are easy to remove without obfuscation but obfuscation defeats the purpose of even being on git

**Comment by coolboy1012141612** [comment]
@hrt come on dont quit :/ pls update
