### ISSUE TITLE
Make a obsfucatde code

### ISSUE THREAD

**Issue by FallingBoi** [hrt/KrunkerMultihack#35]
Maybe u can obsfucatde code to make the ppl cant change the water marks or the code in there, and maybe cau u please solve the "NoAvailableServers" Problem in new 1.5.0 Update, i think. im sorry if i annoyed u :(

**Comment by FallingBoi** [comment]
Dude, u can give a Mega Link or Mediafire link for the cheat, if u dont want to give in github.com, and use that type of code, cause its important to give the credits to the real developers. :)

**Comment by hrt** [comment]
The "problem" for you is that I haven't released the update. Mega / mediafire doesn't matter either since unpacking a chrome extension / code is simple.

**Comment by FallingBoi** [comment]
@hrt I know its very hard to make a hack, and no its my problem, its the problem of the community and i know i just unzip the zip and install the extension, but i dont wanna it now, i wanna u to take ur time and do it whenever u want, i will always wait you.

**Comment by hrt** [comment]
I'm no longer releasing anything publicly yet.
Going down the patreon route for now, https://www.patreon.com/hrt
