### ISSUE TITLE
the bullets dont hit

### ISSUE THREAD

**Issue by coolboy10121416** [hrt/KrunkerMultihack#4]
the aimbot locks on but the bullets are not hitting the player the player predication for the aimbot needs to be fixed

**Comment by coolboy10121416** [comment]
do u have a lerp on the aimbot if u do it needs to be fixed

**Comment by coolboy10121416** [comment]
yep i was correct the player prediction needs to be fix

**Comment by billythejew456** [comment]
its still aimbot stop beng a bitch

**Comment by billythejew456** [comment]
jk

**Comment by hrt** [comment]
Make sure you're using the latest version - if you have 999 bullets then you are using an old version. There is no prediction at the moment, it just aims at what it sees.

The latest version works well with revolver/sniper : there is no recoil control so make sure you leave intervals for recoil to reduce

**Comment by hrt** [comment]
@coolboy10121416 download the new version and try it now with the assault rifle (auto shoot is on)

I have added recoil control and a better visibility -> auto shoot and auto scope
