### ISSUE TITLE
.TMP files keep poppimg up on my pc each file has 2 kilobytes and they each have random ids such as 48he5ehfkfGGD74e4 for exampke how do i fix this issue?????????????

### ISSUE THREAD

**Issue by Crimeloser** [hrt/KrunkerMultihack#49]
please review this issue.

**Comment by hrt** [comment]
Lol that sounds like you installed some viruses

**Comment by hrt** [comment]
and completely unrelated to this repository, where are these tmp files even "popping up"

**Comment by Crimeloser** [comment]
lol

**Comment by Crimeloser** [comment]
let me scan my pc.

**Comment by Crimeloser** [comment]
i will post a screenshot.

**Comment by Crimeloser** [comment]
![2019-08-22 (3)](https://user-images.githubusercontent.com/54376388/63536795-2fbe9300-c4c9-11e9-92d2-8c5c1b0bc2e2.png)

**Comment by Crimeloser** [comment]
that id

**Comment by Crimeloser** [comment]
take a look

**Comment by hrt** [comment]
yeah that's not me
