### ISSUE TITLE
Third Person not working correcly

### ISSUE THREAD

**Issue by C4LLZ** [hrt/KrunkerMultihack#55]
Third person is broken. When enabling Thirdperson mid-game it only stretches the players arms. But when you restart a game or die w third person enabled it fixes itself. Same thing when you have it enabled and whant to turn it off. You see the player model in first person.  
![Skärmbild (1)](https://user-images.githubusercontent.com/33510329/63620532-ce461380-c5f1-11e9-87c4-f7e37c9eb1b3.png)

**Comment by J-Queso** [comment]
from the starts of this hack it does that.

**Comment by hrt** [comment]
@weggethegamer @J-Queso  you need to die/re-spawn once after activating.
