### ISSUE TITLE
How do I make an aimbot and more by using these bypassing stuff?

### ISSUE THREAD

**Issue by able-j** [hrt/KrunkerMultihack#57]
How do I use these modifications to apply on the 1.5.9 krunker.io and the old app.asar u had on the  repo that u deleted?

**Comment by hrt** [comment]
You would have to unpack krunker.ios original app.asar and begin using the bypasses mentioned. 
Otherwise unpack old app.asar and deobfuscate it and update it.

But considering you have to ask this question, I don't think you are ready for this.
