### ISSUE TITLE
yo hi, can I learn from u on hacking Javascript games

### ISSUE THREAD

**Issue by able-j** [hrt/KrunkerMultihack#59]
Can I learn from u about hacking js games? U can respond, or just friend me on yee#5017 (sorry I blocked friend requests before now I dont) I really want to.

**Comment by hrt** [comment]
I'm not a teacher but there's enough resources to learn online yourself.

**Comment by able-j** [comment]
which resources are there what you're referring to? I couldn't find any on javascript games.

**Comment by hrt** [comment]
Learning how js works in the browser in general paired with some knowledge on how games work (e.g. they usually have entity lists with useful information etc.) should be enough. 
Most cheats are just modifying the javascript of the game logic.
