### ISSUE TITLE
How 2 b-hop

### ISSUE THREAD

**Issue by J-Queso** [hrt/KrunkerMultihack#6]
What do u mean with "Perfect bunnyhop / slidejump (hold mouse button 5)"
What is mouse button 5? And btw nice hack dude, keep the good work.

**Comment by hrt** [comment]
it's the side button on my mouse lol, some programs call it "forward".

I might figure out how to make it replace whatever you have as jump bind in the future

**Comment by J-Queso** [comment]
But i dont have mouse gamer

**Comment by hrt** [comment]
I'll add a menu later I guess

**Comment by J-Queso** [comment]
U will add menu? :pepehype: And whats ur discord btw?

**Comment by hrt** [comment]
Pushed menu
