### ISSUE TITLE
auto shoot does not work sometimes

### ISSUE THREAD

**Issue by coolboy10121416** [hrt/KrunkerMultihack#8]
u have to fix auto shoot for semi guns like sniper , revolver shotgun etc

**Comment by coolboy10121416** [comment]
and it need alittle be more work because sometimes it will not work

**Comment by J-Queso** [comment]
we know its hard to make a hack and tired but when u got time, please think about suggestions @hrt

**Comment by hrt** [comment]
Yeah, I've fixed it (always works now) but haven't pushed an update yet because menu in progress

**Comment by hrt** [comment]
@coolboy10121416  download new version
